// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCUGufWjmbD3W1DMnSbPcpOYZ6hjiRnS4',
    appId: '1:618640597187:web:a8532c866e7a4ef65ec276',
    messagingSenderId: '618640597187',
    projectId: 'zami-1082f',
    authDomain: 'zami-1082f.firebaseapp.com',
    databaseURL: 'https://zami-1082f-default-rtdb.firebaseio.com',
    storageBucket: 'zami-1082f.appspot.com',
    measurementId: 'G-WFXD0QP76D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrYrQaufd7PoDDgtD5S1yp0xskZBkB0oo',
    appId: '1:618640597187:android:554835007a2a6bfc5ec276',
    messagingSenderId: '618640597187',
    projectId: 'zami-1082f',
    databaseURL: 'https://zami-1082f-default-rtdb.firebaseio.com',
    storageBucket: 'zami-1082f.appspot.com',
  );
}
